import { Injectable } from '@angular/core';

import { FavouriteProduct } from '@admin-panel-web/features/favourites/types/favourite-product.interface';

import { Observable, of, delay } from 'rxjs';

const MOCK_FAVOURITES: FavouriteProduct[] = [
  {
    id: 'fav-1',
    image: 'https://placehold.co/240x240/4880ff/fff?text=Watch',
    name: 'Apple Watch Series 7',
    description: 'GPS, 41mm aluminium case with sport band, retina display.',
    category: 'Electronic',
    rating: 4.5,
    reviewCount: 320,
    price: 399,
    originalPrice: 459,
    availableColors: ['#333333', '#4880ff', '#00b69b'],
    isFavorite: true,
  },
  {
    id: 'fav-2',
    image: 'https://placehold.co/240x240/ff9f43/fff?text=Headset',
    name: 'Microsoft Headsquare',
    description: 'Wireless headset with active noise cancellation and 30h battery.',
    category: 'Electronic',
    rating: 4.0,
    reviewCount: 184,
    price: 149,
    originalPrice: null,
    availableColors: ['#f93c65', '#ff9f43'],
    isFavorite: true,
  },
  {
    id: 'fav-3',
    image: 'https://placehold.co/240x240/00b69b/fff?text=Dress',
    name: "Women's Casual Wear",
    description: 'Soft cotton blend dress, perfect for spring and summer days.',
    category: 'Fashion',
    rating: 4.7,
    reviewCount: 512,
    price: 89,
    originalPrice: 120,
    availableColors: ['#4880ff', '#00b69b', '#ff9f43', '#333333'],
    isFavorite: true,
  },
  {
    id: 'fav-4',
    image: 'https://placehold.co/240x240/f93c65/fff?text=Phone',
    name: 'Samsung Galaxy A50',
    description: '6.4" FHD+ display, 4000mAh battery, triple rear camera.',
    category: 'Mobile',
    rating: 4.2,
    reviewCount: 278,
    price: 299,
    originalPrice: null,
    availableColors: ['#333333', '#4880ff'],
    isFavorite: true,
  },
  {
    id: 'fav-5',
    image: 'https://placehold.co/240x240/333333/fff?text=Camera',
    name: 'Nikon Z50 Camera',
    description: 'Mirrorless camera with 20.9MP DX-format sensor and 4K video.',
    category: 'Electronic',
    rating: 4.8,
    reviewCount: 142,
    price: 999,
    originalPrice: 1199,
    availableColors: ['#333333'],
    isFavorite: true,
  },
  {
    id: 'fav-6',
    image: 'https://placehold.co/240x240/4880ff/fff?text=Sennheiser',
    name: 'Sennheiser Momentum',
    description: 'Premium over-ear headphones with adaptive noise cancellation.',
    category: 'Electronic',
    rating: 4.6,
    reviewCount: 209,
    price: 349,
    originalPrice: null,
    availableColors: ['#333333', '#f93c65', '#4880ff'],
    isFavorite: true,
  },
  {
    id: 'fav-7',
    image: 'https://placehold.co/240x240/ff9f43/fff?text=Airpods',
    name: 'Apple AirPods Pro',
    description: 'Active noise cancellation, transparency mode and MagSafe case.',
    category: 'Electronic',
    rating: 4.4,
    reviewCount: 631,
    price: 229,
    originalPrice: 249,
    availableColors: ['#ffffff'],
    isFavorite: true,
  },
  {
    id: 'fav-8',
    image: 'https://placehold.co/240x240/00b69b/fff?text=JBL',
    name: 'JBL Flip 6 Speaker',
    description: 'Portable Bluetooth speaker, IP67 waterproof, 12h playtime.',
    category: 'Electronic',
    rating: 4.3,
    reviewCount: 412,
    price: 119,
    originalPrice: null,
    availableColors: ['#333333', '#00b69b', '#4880ff'],
    isFavorite: true,
  },
  {
    id: 'fav-9',
    image: 'https://placehold.co/240x240/f93c65/fff?text=Sneakers',
    name: 'Urban Runner Sneakers',
    description: 'Lightweight mesh upper with cushioned sole for daily comfort.',
    category: 'Fashion',
    rating: 4.1,
    reviewCount: 96,
    price: 79,
    originalPrice: 99,
    availableColors: ['#333333', '#f93c65'],
    isFavorite: true,
  },
  {
    id: 'fav-10',
    image: 'https://placehold.co/240x240/4880ff/fff?text=Backpack',
    name: 'Travel Pro Backpack',
    description: '35L capacity, anti-theft pockets, padded laptop sleeve up to 16".',
    category: 'Accessories',
    rating: 4.5,
    reviewCount: 187,
    price: 65,
    originalPrice: null,
    availableColors: ['#333333', '#4880ff', '#00b69b'],
    isFavorite: true,
  },
  {
    id: 'fav-11',
    image: 'https://placehold.co/240x240/333333/fff?text=Smartband',
    name: 'Mi Smart Band 7',
    description: 'AMOLED display, 14-day battery, 110+ sport modes and SpO2.',
    category: 'Electronic',
    rating: 4.0,
    reviewCount: 354,
    price: 59,
    originalPrice: 79,
    availableColors: ['#333333', '#ff9f43'],
    isFavorite: true,
  },
  {
    id: 'fav-12',
    image: 'https://placehold.co/240x240/ff9f43/fff?text=Mug',
    name: 'Ceramic Coffee Mug Set',
    description: 'Set of 4 handcrafted ceramic mugs, dishwasher and microwave safe.',
    category: 'Home',
    rating: 4.9,
    reviewCount: 76,
    price: 32,
    originalPrice: null,
    availableColors: ['#ffffff', '#333333'],
    isFavorite: true,
  },
];

@Injectable({ providedIn: 'root' })
export class FavouritesRepository {
  public getFavourites(): Observable<FavouriteProduct[]> {
    return of(MOCK_FAVOURITES).pipe(delay(600));
  }
}
